import type { Api, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'payments',  name: 'Payments',       icon: 'payments',  desc: 'Payment processing & billing' },
  { id: 'ai',        name: 'AI / ML',         icon: 'ai',        desc: 'Machine learning & AI models' },
  { id: 'maps',      name: 'Maps & Geo',      icon: 'maps',      desc: 'Location, routing, geolocation' },
  { id: 'messaging', name: 'Messaging',       icon: 'messaging', desc: 'SMS, email, push notifications' },
  { id: 'weather',   name: 'Weather',         icon: 'weather',   desc: 'Forecasts & climate data' },
  { id: 'finance',   name: 'Finance',         icon: 'finance',   desc: 'Stocks, crypto, market data' },
  { id: 'auth',      name: 'Auth & Identity', icon: 'auth',      desc: 'Authentication & SSO' },
  { id: 'data',      name: 'Data',            icon: 'data',      desc: 'Analytics, metrics, insights' },
  { id: 'social',    name: 'Social Media',    icon: 'social',    desc: 'Social platforms & sharing' },
  { id: 'storage',   name: 'Storage & CDN',   icon: 'storage',   desc: 'File storage & delivery' },
  { id: 'search',    name: 'Search',          icon: 'search',    desc: 'Search engines & indexing' },
  { id: 'comms',     name: 'Comms',           icon: 'comms',     desc: 'Voice, video, conferencing' },
];

export const APIS: Api[] = [
  {
    id: 'stripe',
    name: 'Stripe',
    pkg: { js: 'stripe', python: 'stripe', note: 'npm install stripe  /  pip install stripe' },
    description: 'The complete payments platform. Accept payments, build marketplaces, automate revenue management, and manage subscriptions globally.',
    longDesc: 'Stripe is the world\'s leading payment infrastructure. It handles everything from simple one-time charges to complex subscription billing, marketplace payouts, and global payment methods.',
    category: 'payments',
    rating: 4.9, ratingCount: 2847, difficulty: 3,
    pricing: 'pay-per-use', authType: 'API Key',
    docsUrl: 'https://stripe.com/docs',
    views: 89420, trending: true,
    sdks: [
      { name: 'stripe-node',   url: 'https://github.com/stripe/stripe-node',   lang: 'JS'     },
      { name: 'stripe-python', url: 'https://github.com/stripe/stripe-python', lang: 'Python' },
      { name: 'stripe-go',     url: 'https://github.com/stripe/stripe-go',     lang: 'Go'     },
    ],
    ratings: [
      { user: 'mike_dev',   rating: 5, comment: 'Best payments API. Documentation is exceptional.', date: '2025-11-12' },
      { user: 'sarah_b',    rating: 5, comment: 'If every API was this well designed…',             date: '2025-10-28' },
    ],
  },
  {
    id: 'openai',
    name: 'OpenAI API',
    pkg: { js: 'openai', python: 'openai', note: 'npm install openai  /  pip install openai' },
    description: 'Access GPT-4, DALL·E, Whisper, and Embeddings. Build AI-powered apps with state-of-the-art language, image, and audio models.',
    longDesc: 'OpenAI\'s API gives access to GPT-4o, DALL·E 3, Whisper, and text-embedding-3. Build chatbots, coding assistants, image generators, and semantic search.',
    category: 'ai',
    rating: 4.7, ratingCount: 3201, difficulty: 2,
    pricing: 'pay-per-use', authType: 'Bearer Token',
    docsUrl: 'https://platform.openai.com/docs',
    views: 102000, trending: true,
    sdks: [
      { name: 'openai-node',   url: 'https://github.com/openai/openai-node',   lang: 'JS'     },
      { name: 'openai-python', url: 'https://github.com/openai/openai-python', lang: 'Python' },
    ],
    ratings: [
      { user: 'ali_ml', rating: 5, comment: 'Changed the game for building AI products.', date: '2025-11-20' },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude API',
    pkg: { js: '@anthropic-ai/sdk', python: 'anthropic', note: 'npm install @anthropic-ai/sdk  /  pip install anthropic' },
    description: 'Access Claude — safe, helpful, and honest AI. Build with Claude for reasoning, analysis, coding, and complex multi-step tasks.',
    longDesc: 'Anthropic\'s Claude API provides the Claude family of AI models with a 200K token context window. Ideal for document analysis, code review, customer support, and agents.',
    category: 'ai',
    rating: 4.8, ratingCount: 1650, difficulty: 2,
    pricing: 'pay-per-use', authType: 'API Key',
    docsUrl: 'https://docs.anthropic.com',
    views: 72000, trending: true,
    sdks: [
      { name: '@anthropic-ai/sdk', url: 'https://github.com/anthropics/anthropic-sdk-typescript', lang: 'TS'     },
      { name: 'anthropic',         url: 'https://github.com/anthropics/anthropic-sdk-python',     lang: 'Python' },
    ],
    ratings: [
      { user: 'ai_builder', rating: 5, comment: 'Claude\'s reasoning is top tier.',       date: '2025-11-22' },
      { user: 'ml_eng',     rating: 5, comment: 'Streaming API is well-designed.',        date: '2025-11-15' },
    ],
  },
  {
    id: 'auth0',
    name: 'Auth0 (nextjs-auth0)',
    pkg: { js: '@auth0/nextjs-auth0', python: 'authlib', note: 'npm install @auth0/nextjs-auth0  /  pip install authlib' },
    description: 'Drop-in authentication for Next.js. OAuth, OIDC, SAML, MFA, and 30+ social providers with a single package.',
    longDesc: '@auth0/nextjs-auth0 handles auth in Next.js with zero friction — App Router, server components, edge middleware, session management, and protected routes out of the box.',
    category: 'auth',
    rating: 4.6, ratingCount: 1540, difficulty: 4,
    pricing: 'freemium', authType: 'OAuth 2.0 / OIDC',
    docsUrl: 'https://auth0.com/docs/quickstart/webapp/nextjs',
    views: 43800, trending: false,
    sdks: [
      { name: '@auth0/nextjs-auth0', url: 'https://github.com/auth0/nextjs-auth0', lang: 'Next.js' },
      { name: 'node-auth0',          url: 'https://github.com/auth0/node-auth0',   lang: 'Node'    },
    ],
    ratings: [
      { user: 'sam_sec', rating: 5, comment: 'Enterprise-grade auth without the headache.', date: '2025-11-03' },
    ],
  },
  {
    id: 'github',
    name: 'GitHub REST API',
    pkg: { js: '@octokit/rest', python: 'PyGithub', note: 'npm install @octokit/rest  /  pip install PyGithub' },
    description: 'Automate GitHub workflows. Access repos, issues, PRs, actions, and users — all through Octokit\'s fully-typed client.',
    longDesc: '@octokit/rest provides full access to the GitHub REST API with TypeScript types, pagination helpers, and plugin architecture. Build bots, CI tools, and developer dashboards.',
    category: 'data',
    rating: 4.8, ratingCount: 3405, difficulty: 2,
    pricing: 'free', authType: 'OAuth / PAT',
    docsUrl: 'https://docs.github.com/en/rest',
    views: 95000, trending: true,
    sdks: [
      { name: '@octokit/rest', url: 'https://github.com/octokit/rest.js',      lang: 'JS'     },
      { name: 'PyGithub',      url: 'https://github.com/PyGithub/PyGithub',    lang: 'Python' },
    ],
    ratings: [
      { user: 'hacker_bob', rating: 5, comment: 'Incredibly well-documented.', date: '2025-11-18' },
    ],
  },
  {
    id: 'algolia',
    name: 'Algolia Search',
    pkg: { js: 'algoliasearch', python: 'algoliasearch', note: 'npm install algoliasearch  /  pip install algoliasearch' },
    description: 'AI-powered search and discovery. Full-text, vector, and hybrid search with sub-10 ms response times and built-in typo tolerance.',
    longDesc: 'Algolia powers search for 17,000+ companies. Typo-tolerance, faceted filtering, relevance tuning, and AI ranking make it the gold standard for developer-first search.',
    category: 'search',
    rating: 4.7, ratingCount: 980, difficulty: 3,
    pricing: 'freemium', authType: 'API Key',
    docsUrl: 'https://www.algolia.com/doc/',
    views: 27800, trending: true,
    sdks: [
      { name: 'algoliasearch',        url: 'https://github.com/algolia/algoliasearch-client-javascript', lang: 'JS'     },
      { name: 'algoliasearch-python', url: 'https://github.com/algolia/algoliasearch-client-python',     lang: 'Python' },
    ],
    ratings: [
      { user: 'search_nerd', rating: 5, comment: 'Sub-10ms search is not a lie.', date: '2025-11-05' },
    ],
  },
  {
    id: 'polygon',
    name: 'Polygon.io',
    pkg: { js: '@polygon.io/client-js', python: 'polygon-api-client', note: 'npm install @polygon.io/client-js  /  pip install polygon-api-client' },
    description: 'Real-time and historical financial data. Stocks, options, forex, and crypto with tick-level granularity via REST and WebSocket.',
    longDesc: 'Polygon.io provides institutional-grade market data for US equities, options chains, forex, and crypto. Access trades, quotes, aggregates at millisecond resolution.',
    category: 'finance',
    rating: 4.3, ratingCount: 620, difficulty: 4,
    pricing: 'freemium', authType: 'API Key',
    docsUrl: 'https://polygon.io/docs',
    views: 19400, trending: false,
    sdks: [
      { name: '@polygon.io/client-js', url: 'https://github.com/polygon-io/client-js',     lang: 'JS'     },
      { name: 'polygon-api-client',    url: 'https://github.com/polygon-io/client-python', lang: 'Python' },
    ],
    ratings: [
      { user: 'quant_dev', rating: 4, comment: 'Best price-to-data ratio for retail quants.', date: '2025-10-25' },
    ],
  },
  {
    id: 'plaid',
    name: 'Plaid',
    pkg: { js: 'plaid', python: 'plaid-python', note: 'npm install plaid  /  pip install plaid-python' },
    description: 'Connect users\' bank accounts to your app. Transactions, balances, identity, and income verification across 12,000+ institutions.',
    longDesc: 'Plaid is the fintech network layer. Link bank accounts, retrieve transaction history, verify ACH ownership, check balances, and verify income for lending applications.',
    category: 'finance',
    rating: 4.4, ratingCount: 880, difficulty: 6,
    pricing: 'pay-per-use', authType: 'OAuth 2.0',
    docsUrl: 'https://plaid.com/docs',
    views: 31200, trending: true,
    sdks: [
      { name: 'plaid',        url: 'https://github.com/plaid/plaid-node',   lang: 'Node'   },
      { name: 'plaid-python', url: 'https://github.com/plaid/plaid-python', lang: 'Python' },
    ],
    ratings: [
      { user: 'fintech_b', rating: 4, comment: 'Link UI handles bank auth complexity well.', date: '2025-11-02' },
    ],
  },
  {
    id: 'paystack',
    name: 'Paystack',
    pkg: { js: 'paystack-api', python: 'requests', note: 'npm install paystack-api  /  pip install requests' },
    description: 'Payments infrastructure for Africa. Accept cards, bank transfers, mobile money, and recurring subscriptions.',
    longDesc: 'Paystack helps businesses in African markets collect payments, manage customers, verify transactions, and automate billing workflows via a clean REST API.',
    category: 'payments',
    rating: 4.6, ratingCount: 970, difficulty: 3,
    pricing: 'pay-per-use', authType: 'Bearer Token',
    docsUrl: 'https://paystack.com/docs/api/',
    views: 28700, trending: true,
    sdks: [
      { name: 'paystack-api', url: 'https://www.npmjs.com/package/paystack-api', lang: 'Node' },
    ],
    ratings: [
      { user: 'lagos_dev', rating: 5, comment: 'Great DX for African payment flows.', date: '2025-11-09' },
    ],
  },
  {
    id: 'resend',
    name: 'Resend',
    pkg: { js: 'resend', python: 'resend', note: 'npm install resend  /  pip install resend' },
    description: 'Email API built for developers. Send React Email templates or plain HTML with a simple API call and excellent deliverability.',
    longDesc: 'Resend is the modern email API. Write templates in React, send with one function call, and ship with confidence. Designed for great DX and reliable delivery.',
    category: 'messaging',
    rating: 4.8, ratingCount: 780, difficulty: 1,
    pricing: 'freemium', authType: 'API Key',
    docsUrl: 'https://resend.com/docs',
    views: 42000, trending: true,
    sdks: [
      { name: 'resend',        url: 'https://github.com/resend/resend-node',   lang: 'JS'     },
      { name: 'resend-python', url: 'https://github.com/resend/resend-python', lang: 'Python' },
    ],
    ratings: [
      { user: 'ship_fast', rating: 5, comment: 'Replaced SendGrid and never looked back.', date: '2025-11-20' },
    ],
  },
  {
    id: 'twilio',
    name: 'Twilio',
    pkg: { js: 'twilio', python: 'twilio', note: 'npm install twilio  /  pip install twilio' },
    description: 'Cloud communications. Send SMS, make voice calls, build WhatsApp bots, and verify users with OTP globally.',
    longDesc: 'Twilio powers communication for thousands of apps — SMS, voice, WhatsApp, email, and OTP verification through a single platform with global carrier-grade reliability.',
    category: 'messaging',
    rating: 4.5, ratingCount: 1820, difficulty: 4,
    pricing: 'pay-per-use', authType: 'API Key + Secret',
    docsUrl: 'https://www.twilio.com/docs',
    views: 54300, trending: false,
    sdks: [
      { name: 'twilio',        url: 'https://github.com/twilio/twilio-node',   lang: 'Node'   },
      { name: 'twilio-python', url: 'https://github.com/twilio/twilio-python', lang: 'Python' },
    ],
    ratings: [
      { user: 'nate_eng', rating: 5, comment: 'Reliable and feature-rich.', date: '2025-10-15' },
    ],
  },
  {
    id: 'openweather',
    name: 'OpenWeatherMap',
    pkg: { js: 'fetch (REST)', python: 'requests', note: 'No SDK needed — pure REST' },
    description: 'Global weather data. Current conditions, 5-day forecasts, historical data, and air quality for any location on Earth.',
    longDesc: 'OpenWeatherMap covers 200,000+ cities with current weather, hourly/daily forecasts, weather alerts, historical data, and UV index. Free tier suits most applications.',
    category: 'weather',
    rating: 4.2, ratingCount: 920, difficulty: 1,
    pricing: 'freemium', authType: 'API Key',
    docsUrl: 'https://openweathermap.org/api',
    views: 28900, trending: false,
    sdks: [],
    ratings: [
      { user: 'weather_dev', rating: 4, comment: 'Free tier is generous and accurate enough.', date: '2025-11-14' },
    ],
  },
  {
    id: 'google-maps',
    name: 'Google Maps Platform',
    pkg: { js: '@googlemaps/js-api-loader', python: 'googlemaps', note: 'npm install @googlemaps/js-api-loader  /  pip install googlemaps' },
    description: 'Build location-aware apps with maps, routes, places, geocoding, and Street View. Trusted by 5M+ apps worldwide.',
    longDesc: 'Google Maps Platform provides the most accurate mapping data globally — real-time traffic, 200M+ places, turn-by-turn routing, Street View, and global geocoding.',
    category: 'maps',
    rating: 4.4, ratingCount: 2100, difficulty: 3,
    pricing: 'freemium', authType: 'API Key',
    docsUrl: 'https://developers.google.com/maps',
    views: 61200, trending: false,
    sdks: [
      { name: '@googlemaps/js-api-loader', url: 'https://github.com/googlemaps/js-api-loader',                  lang: 'JS'     },
      { name: 'googlemaps',                url: 'https://github.com/googlemaps/google-maps-services-python',    lang: 'Python' },
    ],
    ratings: [
      { user: 'geo_dev', rating: 4, comment: 'Data quality is unmatched.', date: '2025-11-08' },
    ],
  },
  {
    id: 'cloudflare-r2',
    name: 'Cloudflare R2',
    pkg: { js: 'aws-sdk / @aws-sdk/client-s3', python: 'boto3', note: 'npm install @aws-sdk/client-s3  /  pip install boto3' },
    description: 'S3-compatible object storage with zero egress fees. Great for media, backups, and app assets.',
    longDesc: 'Cloudflare R2 provides globally distributed object storage with S3-compatible APIs and zero egress charges, making it ideal for modern file-heavy applications.',
    category: 'storage',
    rating: 4.6, ratingCount: 690, difficulty: 3,
    pricing: 'freemium', authType: 'Access Key / Secret',
    docsUrl: 'https://developers.cloudflare.com/r2/',
    views: 23800, trending: true,
    sdks: [
      { name: '@aws-sdk/client-s3', url: 'https://github.com/aws/aws-sdk-js-v3', lang: 'JS' },
      { name: 'boto3', url: 'https://github.com/boto/boto3', lang: 'Python' },
    ],
    ratings: [
      { user: 'cdn_ops', rating: 5, comment: 'Perfect S3 drop-in for reducing bandwidth bills.', date: '2025-11-10' },
    ],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    pkg: { js: '@supabase/supabase-js', python: 'supabase', note: 'npm install @supabase/supabase-js  /  pip install supabase' },
    description: 'Open source Firebase alternative with Postgres, auth, storage, and realtime APIs.',
    longDesc: 'Supabase bundles database, auth, storage, and realtime subscriptions behind developer-friendly APIs, making full-stack app shipping significantly faster.',
    category: 'data',
    rating: 4.8, ratingCount: 2210, difficulty: 3,
    pricing: 'freemium', authType: 'JWT / API Key',
    docsUrl: 'https://supabase.com/docs',
    views: 68400, trending: true,
    sdks: [
      { name: '@supabase/supabase-js', url: 'https://github.com/supabase/supabase-js', lang: 'JS' },
      { name: 'supabase-py', url: 'https://github.com/supabase-community/supabase-py', lang: 'Python' },
    ],
    ratings: [
      { user: 'builder_ash', rating: 5, comment: 'Postgres + auth + storage in one clean platform.', date: '2025-11-19' },
    ],
  },
  {
    id: 'slack',
    name: 'Slack Web API',
    pkg: { js: '@slack/web-api', python: 'slack_sdk', note: 'npm install @slack/web-api  /  pip install slack_sdk' },
    description: 'Build Slack apps, bots, and workflows. Post messages, respond to events, and automate team operations.',
    longDesc: 'Slack Web API and Events API let you create deeply integrated workplace apps with rich messaging, commands, and automation triggers.',
    category: 'comms',
    rating: 4.5, ratingCount: 1310, difficulty: 4,
    pricing: 'freemium', authType: 'OAuth 2.0',
    docsUrl: 'https://api.slack.com',
    views: 40200, trending: false,
    sdks: [
      { name: '@slack/web-api', url: 'https://github.com/slackapi/node-slack-sdk', lang: 'Node' },
      { name: 'slack_sdk', url: 'https://github.com/slackapi/python-slack-sdk', lang: 'Python' },
    ],
    ratings: [
      { user: 'ops_team', rating: 4, comment: 'Excellent for internal tooling and alerts.', date: '2025-10-30' },
    ],
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    pkg: { js: '@sendgrid/mail', python: 'sendgrid', note: 'npm install @sendgrid/mail  /  pip install sendgrid' },
    description: 'Transactional and marketing email APIs with templates, analytics, and enterprise-grade deliverability.',
    longDesc: 'SendGrid by Twilio provides robust mail delivery, dynamic templates, suppression management, and engagement analytics at scale.',
    category: 'messaging',
    rating: 4.3, ratingCount: 1670, difficulty: 2,
    pricing: 'freemium', authType: 'API Key',
    docsUrl: 'https://docs.sendgrid.com',
    views: 35800, trending: false,
    sdks: [
      { name: '@sendgrid/mail', url: 'https://github.com/sendgrid/sendgrid-nodejs', lang: 'Node' },
      { name: 'sendgrid-python', url: 'https://github.com/sendgrid/sendgrid-python', lang: 'Python' },
    ],
    ratings: [
      { user: 'mailer_dev', rating: 4, comment: 'Stable and battle-tested for transactional workloads.', date: '2025-11-01' },
    ],
  },
  {
    id: 'newsapi',
    name: 'NewsAPI',
    pkg: { js: 'fetch (REST)', python: 'requests', note: 'No SDK needed — pure REST' },
    description: 'Search global news headlines and articles by keyword, source, and date.',
    longDesc: 'NewsAPI aggregates current headlines and historical articles from publishers worldwide, useful for media monitoring and trend analysis.',
    category: 'data',
    rating: 4.1, ratingCount: 510, difficulty: 1,
    pricing: 'freemium', authType: 'API Key',
    docsUrl: 'https://newsapi.org/docs',
    views: 16900, trending: false,
    sdks: [],
    ratings: [
      { user: 'trendwatch', rating: 4, comment: 'Great for quick news integrations.', date: '2025-11-06' },
    ],
  },
  {
    id: 'ipinfo',
    name: 'IPinfo',
    pkg: { js: 'ipinfo', python: 'ipinfo', note: 'npm install ipinfo  /  pip install ipinfo' },
    description: 'IP geolocation, ASN, privacy, and company data for fraud prevention and personalization.',
    longDesc: 'IPinfo helps teams enrich traffic with accurate location and network intelligence used in security, analytics, and localization.',
    category: 'maps',
    rating: 4.4, ratingCount: 430, difficulty: 1,
    pricing: 'freemium', authType: 'Token',
    docsUrl: 'https://ipinfo.io/developers',
    views: 14900, trending: false,
    sdks: [
      { name: 'ipinfo-node', url: 'https://github.com/ipinfo/node', lang: 'Node' },
      { name: 'ipinfo-python', url: 'https://github.com/ipinfo/python', lang: 'Python' },
    ],
    ratings: [
      { user: 'fraud_guard', rating: 5, comment: 'Simple and accurate geolocation signals.', date: '2025-11-11' },
    ],
  },
  {
    id: 'coinbase',
    name: 'Coinbase Developer Platform',
    pkg: { js: 'coinbase', python: 'coinbase', note: 'npm install coinbase  /  pip install coinbase' },
    description: 'Crypto payments, wallets, and onchain integrations with reliable infrastructure APIs.',
    longDesc: 'Coinbase Developer Platform offers APIs for wallet operations, payment rails, and blockchain primitives for production crypto apps.',
    category: 'finance',
    rating: 4.3, ratingCount: 740, difficulty: 5,
    pricing: 'pay-per-use', authType: 'API Key + Secret',
    docsUrl: 'https://docs.cdp.coinbase.com',
    views: 20800, trending: true,
    sdks: [
      { name: 'coinbase-node', url: 'https://github.com/coinbase/coinbase-node', lang: 'Node' },
      { name: 'coinbase-python', url: 'https://github.com/coinbase/coinbase-python', lang: 'Python' },
    ],
    ratings: [
      { user: 'crypto_dev', rating: 4, comment: 'Good primitives for wallet-heavy products.', date: '2025-11-09' },
    ],
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Inference API',
    pkg: { js: '@huggingface/inference', python: 'huggingface_hub', note: 'npm install @huggingface/inference  /  pip install huggingface_hub' },
    description: 'Run open-source LLMs and ML models via hosted inference endpoints.',
    longDesc: 'Hugging Face Inference API gives quick access to thousands of public models for text, vision, and audio tasks without managing GPU infrastructure.',
    category: 'ai',
    rating: 4.6, ratingCount: 1180, difficulty: 2,
    pricing: 'freemium', authType: 'Bearer Token',
    docsUrl: 'https://huggingface.co/docs/api-inference/index',
    views: 46200, trending: true,
    sdks: [
      { name: '@huggingface/inference', url: 'https://github.com/huggingface/huggingface.js', lang: 'JS' },
      { name: 'huggingface_hub', url: 'https://github.com/huggingface/huggingface_hub', lang: 'Python' },
    ],
    ratings: [
      { user: 'oss_ml', rating: 5, comment: 'Best way to test OSS models quickly.', date: '2025-11-17' },
    ],
  },
  {
    id: 'sentry',
    name: 'Sentry',
    pkg: { js: '@sentry/nextjs', python: 'sentry-sdk', note: 'npm install @sentry/nextjs  /  pip install sentry-sdk' },
    description: 'Application monitoring with error tracking, tracing, and replay for faster debugging.',
    longDesc: 'Sentry helps teams detect, triage, and fix issues across frontend and backend with stack traces, performance insights, and release health.',
    category: 'data',
    rating: 4.7, ratingCount: 2420, difficulty: 2,
    pricing: 'freemium', authType: 'DSN / API Token',
    docsUrl: 'https://docs.sentry.io',
    views: 51400, trending: true,
    sdks: [
      { name: '@sentry/nextjs', url: 'https://github.com/getsentry/sentry-javascript', lang: 'Next.js' },
      { name: 'sentry-sdk', url: 'https://github.com/getsentry/sentry-python', lang: 'Python' },
    ],
    ratings: [
      { user: 'bug_hunter', rating: 5, comment: 'Production errors are much easier to resolve now.', date: '2025-11-12' },
    ],
  },
  {
    id: 'posthog',
    name: 'PostHog',
    pkg: { js: 'posthog-js', python: 'posthog', note: 'npm install posthog-js  /  pip install posthog' },
    description: 'Product analytics, feature flags, session replay, and experimentation in one platform.',
    longDesc: 'PostHog combines analytics and experimentation APIs to help engineering teams ship and validate product changes quickly.',
    category: 'data',
    rating: 4.6, ratingCount: 1110, difficulty: 3,
    pricing: 'freemium', authType: 'Project Key / API Token',
    docsUrl: 'https://posthog.com/docs',
    views: 27600, trending: true,
    sdks: [
      { name: 'posthog-js', url: 'https://github.com/PostHog/posthog-js', lang: 'JS' },
      { name: 'posthog-python', url: 'https://github.com/PostHog/posthog-python', lang: 'Python' },
    ],
    ratings: [
      { user: 'pm_eng', rating: 5, comment: 'Great feature flags and analytics combo.', date: '2025-11-04' },
    ],
  },
  {
    id: 'upstash-redis',
    name: 'Upstash Redis',
    pkg: { js: '@upstash/redis', python: 'upstash-redis', note: 'npm install @upstash/redis  /  pip install upstash-redis' },
    description: 'Serverless Redis via HTTP. Ideal for Next.js caching, rate limiting, and queues.',
    longDesc: 'Upstash Redis offers global, serverless Redis with simple REST and SDK access, designed for edge and serverless runtimes.',
    category: 'data',
    rating: 4.7, ratingCount: 980, difficulty: 2,
    pricing: 'freemium', authType: 'Bearer Token',
    docsUrl: 'https://upstash.com/docs/redis',
    views: 30100, trending: true,
    sdks: [
      { name: '@upstash/redis', url: 'https://github.com/upstash/redis-js', lang: 'JS' },
      { name: 'upstash-redis', url: 'https://github.com/upstash/redis-py', lang: 'Python' },
    ],
    ratings: [
      { user: 'edge_builder', rating: 5, comment: 'Perfect for serverless caching and counters.', date: '2025-11-16' },
    ],
  },
  {
    id: 'pinecone',
    name: 'Pinecone',
    pkg: { js: '@pinecone-database/pinecone', python: 'pinecone-client', note: 'npm install @pinecone-database/pinecone  /  pip install pinecone-client' },
    description: 'Managed vector database for semantic search, retrieval, and RAG workloads.',
    longDesc: 'Pinecone provides high-performance vector indexing and filtering primitives for production AI retrieval systems.',
    category: 'search',
    rating: 4.5, ratingCount: 1250, difficulty: 4,
    pricing: 'pay-per-use', authType: 'API Key',
    docsUrl: 'https://docs.pinecone.io',
    views: 33600, trending: true,
    sdks: [
      { name: '@pinecone-database/pinecone', url: 'https://github.com/pinecone-io/pinecone-ts-client', lang: 'TS' },
      { name: 'pinecone-client', url: 'https://github.com/pinecone-io/pinecone-python-client', lang: 'Python' },
    ],
    ratings: [
      { user: 'rag_dev', rating: 4, comment: 'Reliable vector search with good docs.', date: '2025-11-07' },
    ],
  },
  {
    id: 'vercel',
    name: 'Vercel API',
    pkg: { js: 'fetch (REST)', python: 'requests', note: 'No SDK needed — pure REST' },
    description: 'Automate deployments, domains, projects, and environment variables in Vercel.',
    longDesc: 'Vercel API lets teams script deployment workflows and infrastructure operations for frontend and full-stack apps.',
    category: 'data',
    rating: 4.4, ratingCount: 640, difficulty: 3,
    pricing: 'freemium', authType: 'Bearer Token',
    docsUrl: 'https://vercel.com/docs/rest-api',
    views: 21900, trending: false,
    sdks: [],
    ratings: [
      { user: 'platform_dev', rating: 4, comment: 'Great for CI/CD automation around deployments.', date: '2025-10-27' },
    ],
  },
  {
    id: 'cloudinary',
    name: 'Cloudinary',
    pkg: { js: 'cloudinary', python: 'cloudinary', note: 'npm install cloudinary  /  pip install cloudinary' },
    description: 'Media management API with image/video transformations, optimization, and delivery.',
    longDesc: 'Cloudinary makes media pipelines easy with upload APIs, smart transformations, CDN delivery, and asset lifecycle tooling.',
    category: 'storage',
    rating: 4.6, ratingCount: 1750, difficulty: 3,
    pricing: 'freemium', authType: 'API Key + Secret',
    docsUrl: 'https://cloudinary.com/documentation',
    views: 42700, trending: false,
    sdks: [
      { name: 'cloudinary_npm', url: 'https://github.com/cloudinary/cloudinary_npm', lang: 'Node' },
      { name: 'pycloudinary', url: 'https://github.com/cloudinary/pycloudinary', lang: 'Python' },
    ],
    ratings: [
      { user: 'media_ops', rating: 5, comment: 'Transforms and delivery are very developer-friendly.', date: '2025-11-13' },
    ],
  },
  {
    id: 'notion',
    name: 'Notion API',
    pkg: { js: '@notionhq/client', python: 'notion-client', note: 'npm install @notionhq/client  /  pip install notion-client' },
    description: 'Read and write Notion pages/databases to build internal tools and sync workflows.',
    longDesc: 'Notion API supports database queries, page updates, and automation for docs, wikis, and project tracking workflows.',
    category: 'data',
    rating: 4.3, ratingCount: 990, difficulty: 2,
    pricing: 'free', authType: 'Bearer Token',
    docsUrl: 'https://developers.notion.com',
    views: 26300, trending: false,
    sdks: [
      { name: '@notionhq/client', url: 'https://github.com/makenotion/notion-sdk-js', lang: 'JS' },
      { name: 'notion-client', url: 'https://github.com/ramnes/notion-sdk-py', lang: 'Python' },
    ],
    ratings: [
      { user: 'toolsmith', rating: 4, comment: 'Solid API for knowledge-base automation.', date: '2025-11-02' },
    ],
  },
  {
    id: 'linear',
    name: 'Linear GraphQL API',
    pkg: { js: '@linear/sdk', python: 'requests', note: 'npm install @linear/sdk  /  pip install requests' },
    description: 'Issue tracking and project planning API used by modern product teams.',
    longDesc: 'Linear API enables issue automation, workflow integrations, and operational reporting for engineering organizations.',
    category: 'data',
    rating: 4.7, ratingCount: 720, difficulty: 3,
    pricing: 'freemium', authType: 'API Key',
    docsUrl: 'https://developers.linear.app',
    views: 18200, trending: true,
    sdks: [
      { name: '@linear/sdk', url: 'https://github.com/linear/linear', lang: 'TS' },
    ],
    ratings: [
      { user: 'eng_lead', rating: 5, comment: 'Excellent API for issue automation.', date: '2025-11-21' },
    ],
  },
  {
    id: 'discord',
    name: 'Discord API',
    pkg: { js: 'discord.js', python: 'discord.py', note: 'npm install discord.js  /  pip install discord.py' },
    description: 'Build bots and integrations for Discord servers with slash commands and events.',
    longDesc: 'Discord API supports message workflows, automations, moderation tooling, and rich bot interactions for communities and teams.',
    category: 'social',
    rating: 4.6, ratingCount: 1880, difficulty: 3,
    pricing: 'free', authType: 'Bot Token / OAuth2',
    docsUrl: 'https://discord.com/developers/docs',
    views: 55100, trending: true,
    sdks: [
      { name: 'discord.js', url: 'https://github.com/discordjs/discord.js', lang: 'Node' },
      { name: 'discord.py', url: 'https://github.com/Rapptz/discord.py', lang: 'Python' },
    ],
    ratings: [
      { user: 'community_bot', rating: 5, comment: 'Great docs and vibrant ecosystem.', date: '2025-11-18' },
    ],
  },
  {
    id: 'gitlab',
    name: 'GitLab API',
    pkg: { js: 'fetch (REST)', python: 'python-gitlab', note: 'No JS SDK needed — REST  /  pip install python-gitlab' },
    description: 'Automate repositories, CI/CD pipelines, merge requests, and project settings in GitLab.',
    longDesc: 'GitLab API enables end-to-end DevOps automation from source control to pipelines, environments, and release management.',
    category: 'data',
    rating: 4.4, ratingCount: 840, difficulty: 3,
    pricing: 'freemium', authType: 'Personal Access Token',
    docsUrl: 'https://docs.gitlab.com/ee/api/',
    views: 24300, trending: false,
    sdks: [
      { name: 'python-gitlab', url: 'https://github.com/python-gitlab/python-gitlab', lang: 'Python' },
    ],
    ratings: [
      { user: 'devops_sam', rating: 4, comment: 'Powerful API surface for CI orchestration.', date: '2025-10-22' },
    ],
  },
];

export const AI_SUGGESTIONS: Record<string, string[]> = {
  stripe:        ['create a payment intent for $25', 'list recent charges', 'create a customer', 'refund a charge'],
  paystack:      ['initialize a payment transaction', 'verify a transaction by reference', 'create a customer', 'charge a returning customer'],
  openai:        ['stream a chat completion', 'generate an image with DALL-E', 'transcribe audio with Whisper', 'create text embeddings'],
  anthropic:     ['stream a message response', 'analyse a PDF document', 'count tokens in a string', 'build a tool-use agent'],
  auth0:         ['protect a Next.js API route', 'get a management API token', 'list all users', 'verify a JWT'],
  github:        ['list open pull requests for a repo', 'create an issue', 'get repo stargazers', 'fetch latest release'],
  algolia:       ['index a batch of records', 'search with facet filters', 'configure ranking settings', 'delete stale records'],
  polygon:       ['get AAPL daily bars for 2024', 'stream real-time trades via WebSocket', 'fetch an option chain', 'get latest quote'],
  plaid:         ['create a link token', 'exchange public token', 'get 30 days of transactions', 'check real-time balance'],
  resend:        ['send a welcome email', 'send with a React template', 'list sent emails', 'retrieve delivery status'],
  twilio:        ['send an SMS', 'make a voice call', 'send a WhatsApp message', 'send OTP and verify it'],
  openweather:   ['get current weather for a city', 'get 5-day forecast', 'get air quality index', 'get weather by lat/lng'],
  'google-maps': ['geocode an address', 'get directions between two points', 'search for nearby restaurants', 'get place details'],
  'cloudflare-r2': ['upload a file to a bucket', 'generate a signed download URL', 'list objects in a bucket', 'delete an object by key'],
  supabase:      ['insert a row into a table', 'query rows with filters', 'upload a file to storage', 'subscribe to realtime changes'],
  slack:         ['post a message to a channel', 'list public channels', 'send a DM to a user', 'reply in a thread'],
  sendgrid:      ['send a transactional email', 'send a dynamic template email', 'validate an email address', 'check message activity'],
  newsapi:       ['fetch top headlines in US', 'search articles by keyword', 'list articles by source', 'get recent tech news'],
  ipinfo:        ['lookup IP geolocation', 'get ASN details for an IP', 'detect VPN/proxy status', 'resolve company info from IP'],
  coinbase:      ['create a crypto charge', 'get account balances', 'list recent transactions', 'create a wallet address'],
  huggingface:   ['run text generation inference', 'summarize an article', 'classify sentiment', 'generate image caption'],
  sentry:        ['capture an exception manually', 'set user context for errors', 'track performance transaction', 'add release info to events'],
  posthog:       ['capture an analytics event', 'identify a user profile', 'evaluate a feature flag', 'send a group analytics event'],
  'upstash-redis':['set and get cache values', 'increment a rate-limit counter', 'push and pop queue items', 'set a key with TTL'],
  pinecone:      ['upsert vectors in an index', 'query top-k similar vectors', 'delete vectors by id', 'filter vector search by metadata'],
  vercel:        ['list deployments for a project', 'create a deployment', 'set environment variables', 'trigger redeploy from git commit'],
  cloudinary:    ['upload an image asset', 'generate a transformed image URL', 'delete an uploaded asset', 'fetch resource metadata'],
  notion:        ['query a database by filter', 'create a new page', 'update page properties', 'append blocks to a page'],
  linear:        ['list issues for a team', 'create a new issue', 'update issue status', 'query project cycles'],
  discord:       ['send message to a channel', 'register a slash command', 'reply to an interaction event', 'assign a role to a member'],
  gitlab:        ['list merge requests', 'create a pipeline', 'open a new issue', 'get project variables'],
};
